package hibernate;

// Generated 23 févr. 2012 22:45:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Commentaires generated by hbm2java
 */
public class Commentaires implements java.io.Serializable {

	private Integer idCommentaire;
	private Grilles grilles;
	private Utilisateurs utilisateurs;
	private String contenu;
	private Date dateCommente;

	public Commentaires() {
	}

	public Commentaires(Grilles grilles, Utilisateurs utilisateurs,
			String contenu, Date dateCommente) {
		this.grilles = grilles;
		this.utilisateurs = utilisateurs;
		this.contenu = contenu;
		this.dateCommente = dateCommente;
	}

	public Integer getIdCommentaire() {
		return this.idCommentaire;
	}

	public void setIdCommentaire(Integer idCommentaire) {
		this.idCommentaire = idCommentaire;
	}

	public Grilles getGrilles() {
		return this.grilles;
	}

	public void setGrilles(Grilles grilles) {
		this.grilles = grilles;
	}

	public Utilisateurs getUtilisateurs() {
		return this.utilisateurs;
	}

	public void setUtilisateurs(Utilisateurs utilisateurs) {
		this.utilisateurs = utilisateurs;
	}

	public String getContenu() {
		return this.contenu;
	}

	public void setContenu(String contenu) {
		this.contenu = contenu;
	}

	public Date getDateCommente() {
		return this.dateCommente;
	}

	public void setDateCommente(Date dateCommente) {
		this.dateCommente = dateCommente;
	}

}
