package hibernate;

// Generated 23 févr. 2012 22:45:53 by Hibernate Tools 3.4.0.CR1

/**
 * Definitionsfr generated by hbm2java
 */
public class Definitionsfr implements java.io.Serializable {

	private Integer idDefintion;
	private String definition;
	private boolean existe;

	public Definitionsfr() {
	}

	public Definitionsfr(String definition, boolean existe) {
		this.definition = definition;
		this.existe = existe;
	}

	public Integer getIdDefintion() {
		return this.idDefintion;
	}

	public void setIdDefintion(Integer idDefintion) {
		this.idDefintion = idDefintion;
	}

	public String getDefinition() {
		return this.definition;
	}

	public void setDefinition(String definition) {
		this.definition = definition;
	}

	public boolean isExiste() {
		return this.existe;
	}

	public void setExiste(boolean existe) {
		this.existe = existe;
	}

}
