package hibernate;

// Generated 23 févr. 2012 22:45:53 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Dictionnairefr generated by hbm2java
 */
public class Dictionnairefr implements java.io.Serializable {

	private int idMot;
	private String mot;
	private boolean existe;
	private Set synonymesfrs = new HashSet(0);
	private Set grillemotses = new HashSet(0);

	public Dictionnairefr() {
	}

	public Dictionnairefr(int idMot, String mot, boolean existe) {
		this.idMot = idMot;
		this.mot = mot;
		this.existe = existe;
	}

	public Dictionnairefr(int idMot, String mot, boolean existe,
			Set synonymesfrs, Set grillemotses) {
		this.idMot = idMot;
		this.mot = mot;
		this.existe = existe;
		this.synonymesfrs = synonymesfrs;
		this.grillemotses = grillemotses;
	}

	public int getIdMot() {
		return this.idMot;
	}

	public void setIdMot(int idMot) {
		this.idMot = idMot;
	}

	public String getMot() {
		return this.mot;
	}

	public void setMot(String mot) {
		this.mot = mot;
	}

	public boolean isExiste() {
		return this.existe;
	}

	public void setExiste(boolean existe) {
		this.existe = existe;
	}

	public Set getSynonymesfrs() {
		return this.synonymesfrs;
	}

	public void setSynonymesfrs(Set synonymesfrs) {
		this.synonymesfrs = synonymesfrs;
	}

	public Set getGrillemotses() {
		return this.grillemotses;
	}

	public void setGrillemotses(Set grillemotses) {
		this.grillemotses = grillemotses;
	}

}
