package hibernate;

// Generated 23 févr. 2012 22:45:53 by Hibernate Tools 3.4.0.CR1

/**
 * Grillemots generated by hbm2java
 */
public class Grillemots implements java.io.Serializable {

	private GrillemotsId id;
	private Orientationmots orientationmots;
	private Grilles grilles;
	private Dictionnairefr dictionnairefr;
	private int coordX;
	private int coordY;

	public Grillemots() {
	}

	public Grillemots(GrillemotsId id, Orientationmots orientationmots,
			Grilles grilles, Dictionnairefr dictionnairefr, int coordX,
			int coordY) {
		this.id = id;
		this.orientationmots = orientationmots;
		this.grilles = grilles;
		this.dictionnairefr = dictionnairefr;
		this.coordX = coordX;
		this.coordY = coordY;
	}

	public GrillemotsId getId() {
		return this.id;
	}

	public void setId(GrillemotsId id) {
		this.id = id;
	}

	public Orientationmots getOrientationmots() {
		return this.orientationmots;
	}

	public void setOrientationmots(Orientationmots orientationmots) {
		this.orientationmots = orientationmots;
	}

	public Grilles getGrilles() {
		return this.grilles;
	}

	public void setGrilles(Grilles grilles) {
		this.grilles = grilles;
	}

	public Dictionnairefr getDictionnairefr() {
		return this.dictionnairefr;
	}

	public void setDictionnairefr(Dictionnairefr dictionnairefr) {
		this.dictionnairefr = dictionnairefr;
	}

	public int getCoordX() {
		return this.coordX;
	}

	public void setCoordX(int coordX) {
		this.coordX = coordX;
	}

	public int getCoordY() {
		return this.coordY;
	}

	public void setCoordY(int coordY) {
		this.coordY = coordY;
	}

}
