package hibernate;

// Generated 23 févr. 2012 22:45:53 by Hibernate Tools 3.4.0.CR1

/**
 * GrillesutilisateursencoursId generated by hbm2java
 */
public class GrillesutilisateursencoursId implements java.io.Serializable {

	private int idUtilisateur;
	private int idGrille;

	public GrillesutilisateursencoursId() {
	}

	public GrillesutilisateursencoursId(int idUtilisateur, int idGrille) {
		this.idUtilisateur = idUtilisateur;
		this.idGrille = idGrille;
	}

	public int getIdUtilisateur() {
		return this.idUtilisateur;
	}

	public void setIdUtilisateur(int idUtilisateur) {
		this.idUtilisateur = idUtilisateur;
	}

	public int getIdGrille() {
		return this.idGrille;
	}

	public void setIdGrille(int idGrille) {
		this.idGrille = idGrille;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GrillesutilisateursencoursId))
			return false;
		GrillesutilisateursencoursId castOther = (GrillesutilisateursencoursId) other;

		return (this.getIdUtilisateur() == castOther.getIdUtilisateur())
				&& (this.getIdGrille() == castOther.getIdGrille());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdUtilisateur();
		result = 37 * result + this.getIdGrille();
		return result;
	}

}
