package hibernate;

// Generated 23 févr. 2012 22:45:53 by Hibernate Tools 3.4.0.CR1

/**
 * GrillemotsId generated by hbm2java
 */
public class GrillemotsId implements java.io.Serializable {

	private int idGrille;
	private int idMot;
	private int idSynonyme;
	private int idOrientation;

	public GrillemotsId() {
	}

	public GrillemotsId(int idGrille, int idMot, int idSynonyme,
			int idOrientation) {
		this.idGrille = idGrille;
		this.idMot = idMot;
		this.idSynonyme = idSynonyme;
		this.idOrientation = idOrientation;
	}

	public int getIdGrille() {
		return this.idGrille;
	}

	public void setIdGrille(int idGrille) {
		this.idGrille = idGrille;
	}

	public int getIdMot() {
		return this.idMot;
	}

	public void setIdMot(int idMot) {
		this.idMot = idMot;
	}

	public int getIdSynonyme() {
		return this.idSynonyme;
	}

	public void setIdSynonyme(int idSynonyme) {
		this.idSynonyme = idSynonyme;
	}

	public int getIdOrientation() {
		return this.idOrientation;
	}

	public void setIdOrientation(int idOrientation) {
		this.idOrientation = idOrientation;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GrillemotsId))
			return false;
		GrillemotsId castOther = (GrillemotsId) other;

		return (this.getIdGrille() == castOther.getIdGrille())
				&& (this.getIdMot() == castOther.getIdMot())
				&& (this.getIdSynonyme() == castOther.getIdSynonyme())
				&& (this.getIdOrientation() == castOther.getIdOrientation());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdGrille();
		result = 37 * result + this.getIdMot();
		result = 37 * result + this.getIdSynonyme();
		result = 37 * result + this.getIdOrientation();
		return result;
	}

}
