package hibernate;

// Generated 23 févr. 2012 22:45:53 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Langues generated by hbm2java
 */
public class Langues implements java.io.Serializable {

	private Integer idLangue;
	private String nomLangue;
	private Set grilleses = new HashSet(0);

	public Langues() {
	}

	public Langues(String nomLangue) {
		this.nomLangue = nomLangue;
	}

	public Langues(String nomLangue, Set grilleses) {
		this.nomLangue = nomLangue;
		this.grilleses = grilleses;
	}

	public Integer getIdLangue() {
		return this.idLangue;
	}

	public void setIdLangue(Integer idLangue) {
		this.idLangue = idLangue;
	}

	public String getNomLangue() {
		return this.nomLangue;
	}

	public void setNomLangue(String nomLangue) {
		this.nomLangue = nomLangue;
	}

	public Set getGrilleses() {
		return this.grilleses;
	}

	public void setGrilleses(Set grilleses) {
		this.grilleses = grilleses;
	}

}
