package hibernate;

// Generated 23 févr. 2012 22:45:53 by Hibernate Tools 3.4.0.CR1

/**
 * Synonymesfr generated by hbm2java
 */
public class Synonymesfr implements java.io.Serializable {

	private int idSynonyme;
	private Dictionnairefr dictionnairefr;
	private String synonyme;
	private boolean existe;

	public Synonymesfr() {
	}

	public Synonymesfr(int idSynonyme, String synonyme, boolean existe) {
		this.idSynonyme = idSynonyme;
		this.synonyme = synonyme;
		this.existe = existe;
	}

	public Synonymesfr(int idSynonyme, Dictionnairefr dictionnairefr,
			String synonyme, boolean existe) {
		this.idSynonyme = idSynonyme;
		this.dictionnairefr = dictionnairefr;
		this.synonyme = synonyme;
		this.existe = existe;
	}

	public int getIdSynonyme() {
		return this.idSynonyme;
	}

	public void setIdSynonyme(int idSynonyme) {
		this.idSynonyme = idSynonyme;
	}

	public Dictionnairefr getDictionnairefr() {
		return this.dictionnairefr;
	}

	public void setDictionnairefr(Dictionnairefr dictionnairefr) {
		this.dictionnairefr = dictionnairefr;
	}

	public String getSynonyme() {
		return this.synonyme;
	}

	public void setSynonyme(String synonyme) {
		this.synonyme = synonyme;
	}

	public boolean isExiste() {
		return this.existe;
	}

	public void setExiste(boolean existe) {
		this.existe = existe;
	}

}
