package hibernate;

// Generated 23 févr. 2012 22:45:53 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Typegrille generated by hbm2java
 */
public class Typegrille implements java.io.Serializable {

	private Integer idTypeGrille;
	private String nomType;
	private Set grilleses = new HashSet(0);

	public Typegrille() {
	}

	public Typegrille(String nomType) {
		this.nomType = nomType;
	}

	public Typegrille(String nomType, Set grilleses) {
		this.nomType = nomType;
		this.grilleses = grilleses;
	}

	public Integer getIdTypeGrille() {
		return this.idTypeGrille;
	}

	public void setIdTypeGrille(Integer idTypeGrille) {
		this.idTypeGrille = idTypeGrille;
	}

	public String getNomType() {
		return this.nomType;
	}

	public void setNomType(String nomType) {
		this.nomType = nomType;
	}

	public Set getGrilleses() {
		return this.grilleses;
	}

	public void setGrilleses(Set grilleses) {
		this.grilleses = grilleses;
	}

}
