package hibernate;

// Generated 23 févr. 2012 22:45:53 by Hibernate Tools 3.4.0.CR1

/**
 * CasesNoires generated by hbm2java
 */
public class CasesNoires implements java.io.Serializable {

	private CasesNoiresId id;
	private Grilles grilles;

	public CasesNoires() {
	}

	public CasesNoires(CasesNoiresId id, Grilles grilles) {
		this.id = id;
		this.grilles = grilles;
	}

	public CasesNoiresId getId() {
		return this.id;
	}

	public void setId(CasesNoiresId id) {
		this.id = id;
	}

	public Grilles getGrilles() {
		return this.grilles;
	}

	public void setGrilles(Grilles grilles) {
		this.grilles = grilles;
	}

}
