package hibernate;

// Generated 23 févr. 2012 22:45:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Grillesutilisateursencours generated by hbm2java
 */
public class Grillesutilisateursencours implements java.io.Serializable {

	private GrillesutilisateursencoursId id;
	private Grilles grilles;
	private Utilisateurs utilisateurs;
	private Date dateJeu;

	public Grillesutilisateursencours() {
	}

	public Grillesutilisateursencours(GrillesutilisateursencoursId id,
			Grilles grilles, Utilisateurs utilisateurs) {
		this.id = id;
		this.grilles = grilles;
		this.utilisateurs = utilisateurs;
	}

	public Grillesutilisateursencours(GrillesutilisateursencoursId id,
			Grilles grilles, Utilisateurs utilisateurs, Date dateJeu) {
		this.id = id;
		this.grilles = grilles;
		this.utilisateurs = utilisateurs;
		this.dateJeu = dateJeu;
	}

	public GrillesutilisateursencoursId getId() {
		return this.id;
	}

	public void setId(GrillesutilisateursencoursId id) {
		this.id = id;
	}

	public Grilles getGrilles() {
		return this.grilles;
	}

	public void setGrilles(Grilles grilles) {
		this.grilles = grilles;
	}

	public Utilisateurs getUtilisateurs() {
		return this.utilisateurs;
	}

	public void setUtilisateurs(Utilisateurs utilisateurs) {
		this.utilisateurs = utilisateurs;
	}

	public Date getDateJeu() {
		return this.dateJeu;
	}

	public void setDateJeu(Date dateJeu) {
		this.dateJeu = dateJeu;
	}

}
