package hibernate;

// Generated 23 févr. 2012 22:45:53 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Orientationmots generated by hbm2java
 */
public class Orientationmots implements java.io.Serializable {

	private Integer idOrientation;
	private String nomOrientation;
	private Set grillemotses = new HashSet(0);

	public Orientationmots() {
	}

	public Orientationmots(String nomOrientation) {
		this.nomOrientation = nomOrientation;
	}

	public Orientationmots(String nomOrientation, Set grillemotses) {
		this.nomOrientation = nomOrientation;
		this.grillemotses = grillemotses;
	}

	public Integer getIdOrientation() {
		return this.idOrientation;
	}

	public void setIdOrientation(Integer idOrientation) {
		this.idOrientation = idOrientation;
	}

	public String getNomOrientation() {
		return this.nomOrientation;
	}

	public void setNomOrientation(String nomOrientation) {
		this.nomOrientation = nomOrientation;
	}

	public Set getGrillemotses() {
		return this.grillemotses;
	}

	public void setGrillemotses(Set grillemotses) {
		this.grillemotses = grillemotses;
	}

}
