package hibernate;

// Generated 23 févr. 2012 22:45:53 by Hibernate Tools 3.4.0.CR1

/**
 * Themes generated by hbm2java
 */
public class Themes implements java.io.Serializable {

	private Integer idTheme;
	private String nomTheme;

	public Themes() {
	}

	public Themes(String nomTheme) {
		this.nomTheme = nomTheme;
	}

	public Integer getIdTheme() {
		return this.idTheme;
	}

	public void setIdTheme(Integer idTheme) {
		this.idTheme = idTheme;
	}

	public String getNomTheme() {
		return this.nomTheme;
	}

	public void setNomTheme(String nomTheme) {
		this.nomTheme = nomTheme;
	}

}
